"""
load_to_clickhouse.py
──────────────────────
Loads CSVs generated by generate_data.py into ClickHouse raw tables.

Strategy: upload CSV files directly to ClickHouse via HTTP (FORMAT CSVWithNames).
ClickHouse parses types natively — no pandas type-guessing, no NaN issues.

Usage:
  pip install python-dotenv
  python ingestion/load_to_clickhouse.py
"""

import os
import sys
import time
import urllib.request
import urllib.parse
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

CH_HOST     = os.getenv("CLICKHOUSE_HOST", "localhost")
CH_PORT     = int(os.getenv("CLICKHOUSE_PORT", "8443"))
CH_USER     = os.getenv("CLICKHOUSE_USER", "default")
CH_PASSWORD = os.getenv("CLICKHOUSE_PASSWORD", "")
CH_BASE_URL = f"https://{CH_HOST}:{CH_PORT}"

DATA_DIR = Path(__file__).parent / "data"


def ch_query(sql: str):
    """Run a DDL/command query (no result needed)."""
    url = f"{CH_BASE_URL}/"
    req = urllib.request.Request(url, data=sql.encode(), method="POST")
    req.add_header("X-ClickHouse-User", CH_USER)
    req.add_header("X-ClickHouse-Key", CH_PASSWORD)
    try:
        with urllib.request.urlopen(req) as resp:
            return resp.read().decode().strip()
    except urllib.error.HTTPError as e:
        raise Exception(e.read().decode())


def ping():
    """Verify connection to ClickHouse."""
    try:
        result = ch_query("SELECT 1")
        assert result == "1"
        print(f"✓ Connected to ClickHouse at {CH_HOST}:{CH_PORT}")
    except Exception as e:
        print(f"✗ Cannot connect to ClickHouse: {e}")
        print("  Check your .env file — CLICKHOUSE_HOST, CLICKHOUSE_PASSWORD")
        sys.exit(1)


def load_table(csv_file: Path, table_name: str):
    """Upload a CSV file directly to ClickHouse using FORMAT CSVWithNames.
    ClickHouse handles all type casting — no pandas type issues."""

    if not csv_file.exists():
        print(f"  ✗ File not found: {csv_file}  (run generate_data.py first)")
        return

    print(f"\nLoading {csv_file.name} → raw.{table_name}")
    start = time.time()

    # Truncate first (idempotent)
    ch_query(f"TRUNCATE TABLE IF EXISTS raw.{table_name}")

    # Upload CSV directly — ClickHouse reads the header row for column names
    query = f"INSERT INTO raw.{table_name} FORMAT CSVWithNames"
    url   = f"{CH_BASE_URL}/?query={urllib.parse.quote(query)}"

    with open(csv_file, "rb") as f:
        data = f.read()

    req = urllib.request.Request(url, data=data, method="POST")
    req.add_header("X-ClickHouse-User", CH_USER)
    req.add_header("X-ClickHouse-Key", CH_PASSWORD)
    req.add_header("Content-Type", "text/plain; charset=utf-8")

    try:
        with urllib.request.urlopen(req) as resp:
            resp.read()
    except urllib.error.HTTPError as e:
        raise Exception(f"Insert failed: {e.read().decode()}")

    elapsed = time.time() - start
    count   = ch_query(f"SELECT count() FROM raw.{table_name}")
    print(f"  ✓ {int(count):,} rows loaded in {elapsed:.1f}s")


def verify_counts():
    """Print row counts for all raw tables."""
    print("\n" + "─" * 40)
    print("Row counts in raw schema:")
    tables = ["campaigns", "creatives", "ad_daily_stats", "skan_postbacks", "iap_events"]
    for tbl in tables:
        try:
            count = ch_query(f"SELECT count() FROM raw.{tbl}")
            print(f"  raw.{tbl:20s}  {int(count):>10,} rows")
        except Exception as e:
            print(f"  raw.{tbl:20s}  ERROR: {e}")
    print("─" * 40)


if __name__ == "__main__":
    print("\n" + "=" * 50)
    print("  ClickHouse Data Loader")
    print("=" * 50)

    ping()

    load_table(DATA_DIR / "campaigns.csv",      "campaigns")
    load_table(DATA_DIR / "creatives.csv",      "creatives")
    load_table(DATA_DIR / "ad_daily_stats.csv", "ad_daily_stats")
    load_table(DATA_DIR / "skan_postbacks.csv", "skan_postbacks")
    load_table(DATA_DIR / "iap_events.csv",     "iap_events")

    verify_counts()

    print("\n✓ All data loaded. Next step: cd ../dbt && dbt run --profiles-dir .")
