-- ─────────────────────────────────────────────────────────────────────────────
-- Raw landing tables — schema mirrors the CSV files generated by generate_data.py
-- MergeTree engine: ClickHouse's primary table engine, great for analytics.
-- ORDER BY clause = the primary sort key (how ClickHouse stores data on disk).
-- ─────────────────────────────────────────────────────────────────────────────

-- Campaigns: paid UA campaigns across networks
CREATE TABLE IF NOT EXISTS raw.campaigns (
    campaign_id     String,
    campaign_name   String,
    network         String,        -- Meta, Google UAC, Apple Search Ads, TikTok, Snap
    objective       String,        -- app_installs, app_purchases
    country         String,        -- US, GB, DE, FR, AU, CA
    daily_budget    Float64,       -- USD
    start_date      Date,
    end_date        Nullable(Date),
    loaded_at       DateTime DEFAULT now()
) ENGINE = MergeTree()
ORDER BY (network, campaign_id);


-- Creatives: individual ad creatives (images, videos)
CREATE TABLE IF NOT EXISTS raw.creatives (
    creative_id     String,
    campaign_id     String,
    creative_name   String,
    format          String,        -- video_15s, video_30s, static_image, carousel
    size            String,        -- 9x16, 1x1, 4x5
    launch_date     Date,
    loaded_at       DateTime DEFAULT now()
) ENGINE = MergeTree()
ORDER BY (campaign_id, creative_id);


-- Ad Daily Stats: daily delivery metrics per creative (MMP / ad network export format)
-- This is the core table for creative burnout analysis
CREATE TABLE IF NOT EXISTS raw.ad_daily_stats (
    stat_date       Date,
    campaign_id     String,
    creative_id     String,
    network         String,
    country         String,
    impressions     UInt64,
    clicks          UInt64,
    spend_usd       Float64,
    installs        UInt64,         -- click-attributed installs (non-SKAN)
    loaded_at       DateTime DEFAULT now()
) ENGINE = MergeTree()
ORDER BY (stat_date, campaign_id, creative_id)
PARTITION BY toYYYYMM(stat_date);  -- partition by month for efficient time-range queries


-- SKAN Postbacks: iOS 14+ privacy-preserving attribution signal
-- One postback per install cohort bucket; no user-level data
CREATE TABLE IF NOT EXISTS raw.skan_postbacks (
    postback_id         String,
    install_date        Date,
    campaign_id         String,
    creative_id         String,
    network             String,
    country             String,
    skan_version        String,     -- 3.0 or 4.0
    conversion_value    UInt8,      -- 0-63 (SKAN 3) or fine/coarse values (SKAN 4)
    postback_sequence   UInt8,      -- 1, 2, or 3 (SKAN 4 has up to 3 postbacks)
    privacy_threshold   String,     -- none | low | medium (SKAN 4)
    loaded_at           DateTime DEFAULT now()
) ENGINE = MergeTree()
ORDER BY (install_date, campaign_id, creative_id)
PARTITION BY toYYYYMM(install_date);


-- IAP Events: in-app purchases (revenue events, anonymized / cohort-level)
CREATE TABLE IF NOT EXISTS raw.iap_events (
    event_id        String,
    install_date    Date,           -- cohort date (not user_id — privacy-safe)
    event_date      Date,
    campaign_id     String,
    creative_id     String,
    network         String,
    country         String,
    event_type      String,         -- trial_start, subscription_start, subscription_renew, purchase
    product_id      String,         -- weekly_sub, monthly_sub, annual_sub, lifetime
    revenue_usd     Float64,
    loaded_at       DateTime DEFAULT now()
) ENGINE = MergeTree()
ORDER BY (install_date, event_date, campaign_id)
PARTITION BY toYYYYMM(install_date);
